# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5460439531b2c106c6b2b7af3db73d84c55face2dc688a1a9762de9f888b4f20783f79a2f6db14810d383ec4ca2db8d7600cb6ab5c8c87cbd687d2662c382805

test:
  secret_key_base: 7ad1041e953b17bde77e6898cfa5fcc9ce1d87e2711e40db69b5b0327b0ceeb92cacb1b3e96cf765248500a1caf749d9da873b37fa42d19769d9b38eaba51607

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
